default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  #host: localhost

development:
  <<: *default
  database: example_development
  #username: postgres
  password: password
  #host: localhost

test:
  <<: *default
  database: example_test
  username: postgres
  password: 'postgres'

production:
  <<: *default
  database: example_production
  #username: rails

#  password: <%= ENV['EXAMPLE_DATABASE_PASSWORD'] %>
  #username: bablu_dev
  password: 'password'